[tool.poetry]
name = "wanda"
version = "0.59.4"
description = "Set wallpapers with keywords or randomly"
authors = ["kshib <ksyko@pm.me>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/kshib/wanda"
repository = "https://gitlab.com/kshib/wanda"
keywords=["wallpaper", "reddit", "wallhaven","unsplash","termux"]

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/kshib/wanda/-/issues"

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.8.0"
cloudscraper = "^1.2.60"
Pillow = "^9.1.0"
screeninfo = "^0.8"
colorthief = "^0.2.1"
filetype = "^1.0.13"
musicbrainzngs = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
mypy = "^0.950"
pytest-xdist = "^2.5.0"
pytest-cov = "^3.0.0"
pytest-rerunfailures = "^10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wanda = "wanda.wanda:run"